# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install phantomjs package
      run: |
        sudo apt-get update
        sudo apt-get install phantomjs
    - name: Run tests
      run: sbt -J-Xms512M -J-Xmx2G -J-Xss2M -J-XX:MaxMetaspaceSize=1024M scalastyle +test headerCheck test:headerCheck +it:test doc
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
#   - name: Upload dependency graph
#     uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91

